template: resume
profile: default

include_experience:
  - id: meridian-data-scientist
    bullets:
      - meridian-ds-etl-pipelines
      - meridian-ds-predictive-models
  - id: slice-jr-data-scientist
    bullets:
      - slice-ds-predictive-models
      - slice-ds-etl-pipelines

include_projects:
  - id: passfx
    bullets:
      - passfx-security
  - id: techpulse
    bullets:
      - techpulse-pipeline
